print ()
nome_aparelho = input ("Qual aparelho utilzaremos?")
print ()
potencia = int (input (f"Qual a  potencia de {nome_aparelho} em Watts (W)?"))
print ()
tempo = int (input (f"Em média, quantas horas diárias utiliza-se {nome_aparelho}?"))
print ()
consumo = int((tempo * potencia * 30) / 1000) 
custo = (consumo * 0.90)
print ()
print ("---------- Consumo ----------")
print ()
print (f"aparelho: {nome_aparelho}")
print  ()
print (f"consumo: {consumo} Kw/h")
print ()
print (f"gasto: R$ {custo: .2f}")